apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adaptor.fullname" . }}-config
  labels:
    {{- include "adaptor.labels" . | nindent 4 }}
data:
  config.yml: |
    env: {{ .Values.config.env }}
    logLevel: {{ .Values.config.logLevel }}
    
    wagerSet:
    {{- range .Values.config.wagerSet }}
      - {{ . }}
    {{- end }}

    engine:
      rtp: {{ .Values.engine.rtp }}
      debug: {{ .Values.engine.debug }}
      isCheatsAvailable: {{ .Values.engine.isCheatsAvailable }}
      mockRng: {{ .Values.engine.mockRng }}
      volatility: {{ .Values.engine.volatility }}

    server:
      host: "0.0.0.0"
      port: 7010
      readTimeout: 30s
      writeTimeout: 30s

    websocket:
      maxProcessingTime: 10000ms
      readBufferSize: 1024
      writeBufferSize: 1024

    tracer:
      disabled: {{ .Values.tracer.disabled }}
      url: {{ .Values.tracer.url }}
      serviceName: {{ .Values.tracer.serviceName }}

    overlord:
      host: {{ .Values.services.overlord.host }}
      port: {{ .Values.services.overlord.port }}
      isSecure: {{ .Values.services.overlord.isSecure }}

    history:
      host: {{ .Values.services.history.host }}
      port: {{ .Values.services.history.port }}
      isSecure: {{ .Values.services.history.isSecure }}

    rng:
      host: {{ .Values.services.rng.host }}
      port: {{ .Values.services.rng.port }}
      maxProcessingTime: 30000ms

    redis:
      host: {{ .Values.redis.host }}
      port: {{ .Values.redis.port }}
      dB: {{ .Values.redis.database }}
      pass: {{ .Values.redis.password | quote }}
      prefix: {{ .Values.redis.prefix | quote }}

    mysql:
      host: {{ .Values.mysql.host }}
      port: {{ .Values.mysql.port }}
      name: {{ .Values.mysql.database }}
      user: {{ .Values.mysql.user }}
      pass: {{ .Values.mysql.password | quote }}

    game:
      availableGames:
      {{- range .Values.games.availableGames }}
        - {{ . }}
      {{- end }}

    gameMapping:
      {{- range $key, $value := .Values.games.gameMapping }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}