replicaCount: 1

image:
  repository: rg.fr-par.scw.cloud/ejaw/rng-api
  pullPolicy: IfNotPresent
  tag: "0.0.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  fsGroup: 0

securityContext:
  privileged: true
  allowPrivilegeEscalation: true
  runAsUser: 0
  runAsNonRoot: false
  capabilities:
    add:
      - ALL

service:
  type: ClusterIP
  grpc:
    port: 7700
    targetPort: 7700
  http:
    port: 7710
    targetPort: 7710

resources:
  requests:
    cpu: 300m
    memory: 300Mi
  limits:
    cpu: 1000m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

volumes:
  - name: config
    configMap:
      name: rng-config
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 1Gi

volumeMounts:
  - name: config
    mountPath: /vault/secrets/config.yml
    subPath: config.yml
    readOnly: true
  - name: dshm
    mountPath: /dev/shm

nodeSelector: {}

tolerations: []

affinity: {}

config:
  http:
    host: "0.0.0.0"
    port: 7710
    maxProcessingTime: 30000
  grpc:
    host: "0.0.0.0"
    port: 7700
    maxProcessingTime: 30000
