apiVersion: v1
kind: Service
metadata:
  name: {{ include "launch.fullname" . }}
  labels:
    {{- include "launch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: {{ .Values.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "launch.selectorLabels" . | nindent 4 }}
---
# Headless service for internal communication
apiVersion: v1
kind: Service
metadata:
  name: launch
  labels:
    {{- include "launch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    {{- include "launch.selectorLabels" . | nindent 4 }}
