apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pfr.fullname" . }}-config
  labels:
    {{- include "pfr.labels" . | nindent 4 }}
data:
  config.yml: |
    server:
      host: 0.0.0.0
      port: 7610
      readTimeout: 30s
      writeTimeout: 30s
      maxProcessingTime: 30000ms

    rpc:
      host: 0.0.0.0
      port: 7600
      maxProcessingTime: 30000ms

    overlord:
      host: {{ .Values.config.overlord.host }}
      port: {{ .Values.config.overlord.port }}

    database:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      name: {{ .Values.database.name }}
      user: {{ .Values.database.user }}
      pass: {{ .Values.database.password }}
      connectionTimeout: {{ .Values.database.connectionTimeout | quote }}
      compression: {{ .Values.database.compression | quote }}
      pingInterval: {{ .Values.database.pingInterval | quote }}
      minConnections: {{ .Values.database.minConnections }}
      maxConnections: {{ .Values.database.maxConnections }}

    tracer:
      disabled: {{ .Values.tracer.disabled }}
      url: {{ .Values.tracer.url }}
      serviceName: {{ .Values.tracer.serviceName }}

    integrators:
      ninjagaming_lb:
        apiSecret: {{ .Values.integrators.ninjagaming.apiSecret }}
      direct:
        mockdirect:
          apiKey: {{ .Values.integrators.direct.apiKey }}
          apiSecret: {{ .Values.integrators.direct.apiSecret }}
          url: {{ .Values.integrators.direct.url }}
          withLogs: {{ .Values.integrators.direct.withLogs }}
      mock: null

    lemonWhiteList: []