apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    component: client
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.client.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}
    component: client
