apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: cat-mansion
    component: client
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.client.port }}
    targetPort: {{ .Values.service.client.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: cat-mansion
    component: client
