apiVersion: v2
name: launch
description: RGS Game launcher service
type: application
version: 1.0.0
appVersion: "1.0.37"
keywords:
  - rgs
  - launch
  - core-service
home:  https://github.com/kay-ninja/rgs-k8s
maintainers:
  - name: Platform Team
    email: kayode@ninjagaming.com
