apiVersion: v2
name: launch
description: RGS Launch Service - Game Launch Management
type: application
version: 1.0.0
appVersion: "1.1.127"
keywords:
  - rgs
  - launch
  - game-launch
  - core-service
home: https://github.com/your-repo/rgs-k8s
maintainers:
  - name: Platform Team
    email: your-email@example.com
