replicaCount: 2

server:
  image:
    repository: paper-toss-server
    tag: latest
    pullPolicy: IfNotPresent

client:
  image:
    repository: paper-toss-client
    tag: latest
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  serverPort: 8000
  clientPort: 80

resources:
  server:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  client:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
