# Office Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "office.fullname" . }}-server
  labels:
    {{- include "office.labels" . | nindent 4 }}
    component: server
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "office.selectorLabels" . | nindent 6 }}
      component: server
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.secretsEnabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "office.selectorLabels" . | nindent 8 }}
        component: server
        app: office
        version: {{ .Values.server.image.tag }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "office.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: office-server
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.server.image.registry }}/{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        ports:
        - name: grpc
          containerPort: {{ .Values.config.rpc.port }}
          protocol: TCP
        - name: http
          containerPort: {{ .Values.config.server.port }}
          protocol: TCP
        env:
        - name: NODE_ENV
          value: {{ .Values.config.env }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.secretsEnabled }}
        envFrom:
        - secretRef:
            name: {{ include "office.fullname" . }}-secret
            optional: true
        {{- end }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources.server | nindent 12 }}
        volumeMounts:
        - name: config
          mountPath: /app
          readOnly: true
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: config
        configMap:
          name: {{ include "office.fullname" . }}-config
          items:
          - key: config
            path: config
      - name: tmp
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- if .Values.client.enabled }}
# Office Client Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "office.fullname" . }}-client
  labels:
    {{- include "office.labels" . | nindent 4 }}
    component: client
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "office.selectorLabels" . | nindent 6 }}
      component: client
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "office.selectorLabels" . | nindent 8 }}
        component: client
        app: office-client
        version: {{ .Values.client.image.tag }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "office.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: office-client
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.client.image.registry }}/{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
        imagePullPolicy: {{ .Values.client.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources.client | nindent 12 }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
        - name: cache
          mountPath: /var/cache/nginx
        - name: run
          mountPath: /var/run
      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "office.fullname" . }}-nginx-config
          items:
          - key: default.conf
            path: default.conf
      - name: cache
        emptyDir: {}
      - name: run
        emptyDir: {}
{{- end }}