{{- if .Values.client.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "office.fullname" . }}-nginx-config
  labels:
    {{- include "office.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        listen [::]:80;
        server_name localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
{{- end }}