apiVersion: v1
kind: Service
metadata:
  name: {{ include "office.fullname" . }}-server
  labels:
    {{- include "office.labels" . | nindent 4 }}
    component: server
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: {{ .Values.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "office.selectorLabels" . | nindent 4 }}
    component: server
---
# Headless service for internal communication
apiVersion: v1
kind: Service
metadata:
  name: office
  labels:
    {{- include "office.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    {{- include "office.selectorLabels" . | nindent 4 }}
    component: server
---
{{- if .Values.client.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "office.fullname" . }}-client
  labels:
    {{- include "office.labels" . | nindent 4 }}
    component: client
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.clientPort }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    {{- include "office.selectorLabels" . | nindent 4 }}
    component: client
{{- end }}
