---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: rgs-infrastructure
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        args:
        - redis-server
        - --protected-mode
        - "no"
        - --appendonly
        - "no"
        - --save
        - ""
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: rgs-infrastructure
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
