gameSlug: cyprus-dede5000

replicaCount: 2

imagePullSecrets:
  - name: docker-registry-credentials

server:
  image:
    registry: ninjargs
    repository: cyprus-go-server
    tag: "1.0.10"
    pullPolicy: IfNotPresent
  port: 8000

client:
  image:
    registry: ninjargs
    repository: dede5000-client
    tag: "cyprus-go-server"
    pullPolicy: IfNotPresent
  port: 8089

service:
  type: ClusterIP

resources:
  server:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  client:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Server configuration
config:
  # HTTP server settings
  http:
    host: 0.0.0.0
    port: 8000
    readTimeout: 30s
    writeTimeout: 30s
    maxProcessingTime: 60000

  # Service endpoints - updated for Kubernetes
  overlord:
    host: overlord-service.rgs-core.svc.cluster.local
    port: 7500
    isSecure: false

  history:
    host: history-service.rgs-core.svc.cluster.local
    port: 7200
    isSecure: false

  rng:
    client: simple
    host: rng-service-grpc.rgs-core.svc.cluster.local
    port: 7700
    isSecure: false
    maxProcessingTime: 30000ms

# Game-specific configuration (dede5000.yaml)
gameConfig:
  info:
    name: dede5000
    rtp:
      base: 94
      game: 94.37
      ante: 94.22
      buyBonus: 94.38
      max: 94.38
      min: 94.22
    coin:
      defaultValue: 1
      min: 1
      max: 1
      numberOfCoins: 1
      defaultCoins: 1
      fixed: true
    payLines:
      number: 1
      numberFreeSpin: 1
      type: fixed
    multipliers:
      ante: 1.3
      buyBonus: 100
    matrix:
      rows: 5
      cols: 6
    maxWinCapacity: 5000

  modes:
    normal:
      transitions:
        - toMode: bonus
          config:
            condition:
              kind: dede-minSymbolCount
              config:
                symbol: SCATTER
                minCount: 4
            effects:
              - kind: dede-reelSetChange
                config: {}

      cycle:
        kind: singleRun
        config: {}
        runner:
          executionBlocks:
            - executionStrategy:
                kind: singleRun
                config: {}
              stages:
                - context: dede5000
                  algorithm:
                    id: dede-spin.new
                  effects: []
                - context: dede5000
                  algorithm:
                    id: dede-window.buildFromStops

            - executionStrategy:
                kind: loopUntilExitCondition
                config:
                  maxIterations: 11
                  condition:
                    kind: dede-noMoreWin
                    config: {}
              stages:
                - context: dede5000
                  priority: 0
                  algorithm:
                    id: dede-symbol.countWin
                - context: dede5000
                  priority: 1
                  algorithm:
                    id: dede-window.removeWinSymbolsAndCollapseFromAbove

            - executionStrategy:
                kind: singleRun
                config: {}
              stages:
                - context: dede5000
                  algorithm:
                    id: dede-checkForScatters
                - context: dede5000
                  algorithm:
                    id: dede-checkForMultipliers

    bonus:
      cycle:
        kind: loop
        config:
          baseIterations: 15
          bonusIterations:
            kind: dede-extraOnSymbolCount
            config:
              symbol: SCATTER
              minCount: 3
              extraRounds: 5
        runner:
          executionBlocks:
            - executionStrategy:
                kind: singleRun
                config: {}
              stages:
                - context: dede5000
                  algorithm:
                    id: dede-spin.new
                  effects: []
                - context: dede5000
                  algorithm:
                    id: dede-window.buildFromStops

            - executionStrategy:
                kind: loopUntilExitCondition
                config:
                  maxIterations: 11
                  condition:
                    kind: dede-noMoreWin
                    config: {}
              stages:
                - context: dede5000
                  priority: 0
                  algorithm:
                    id: dede-symbol.countWin
                - context: dede5000
                  priority: 1
                  algorithm:
                    id: dede-window.removeWinSymbolsAndCollapseFromAbove

            - executionStrategy:
                kind: singleRun
                config: {}
              stages:
                - context: dede5000
                  algorithm:
                    id: dede-checkForScatters
                - context: dede5000
                  algorithm:
                    id: dede-checkForMultipliers

# Client configuration (addon.js)
clientConfig:
  serverIP: "https://xtechgaming.com/cyprus-dede5000/api"
  siteCode: "SCNCSSC"
  logsPath: "https://xtechgaming.com/history"
