apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange.fullname" . }}-config
  labels:
    {{- include "exchange.labels" . | nindent 4 }}
data:
  config: |
    server:
      host: "0.0.0.0"
      port: 7110
      readTimeout: "30s"
      writeTimeout: "30s"

    rpc:
      host: 0.0.0.0
      port: 7100
      maxProcessingTime: 30000ms

    backoffice:
      host: {{ .Values.config.backoffice.host }}
      port: {{ .Values.config.backoffice.port }}
      isSecure: {{ .Values.config.backoffice.isSecure }}

    database:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      name: {{ .Values.database.name }}
      user: {{ .Values.database.user }}
      pass: {{ .Values.database.password }}
      connectionTimeout: {{ .Values.database.connectionTimeout | quote }}
      compression: {{ .Values.database.compression | quote }}
      pingInterval: {{ .Values.database.pingInterval | quote }}
      minConnections: {{ .Values.database.minConnections }}
      maxConnections: {{ .Values.database.maxConnections }}

    xe:
      id: {{ .Values.xe.id }}
      key: {{ .Values.xe.key }}

    exchange:
      baseURL: {{ .Values.exchange.baseURL | quote }}
      enabled: {{ .Values.exchange.enabled }}

    tracer:
      disabled: {{ .Values.tracer.disabled }}
      url: {{ .Values.tracer.url }}
      serviceName: {{ .Values.tracer.serviceName }}