apiVersion: v2
name: exchange
description: RGS Exchange Service - Currency and wallet management
type: application
version: 1.0.0
appVersion: "1.0.52"
keywords:
  - rgs
  - exchange
  - wallet
  - core-service
home:  https://github.com/kay-ninja/rgs-k8s
maintainers:
  - name: Platform Team
    email: kayode@ninjagaming.com
