# Default values for exchange service
replicaCount: 2

image:
  repository: rg.fr-par.scw.cloud/ejaw/exchange
  tag: "1.0.21"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: docker-registry-credentials

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"
  prometheus.io/scrape: "true"
  prometheus.io/port: "7110"

podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  fsGroup: 0

securityContext:
  privileged: true
  allowPrivilegeEscalation: true
  runAsUser: 0
  runAsNonRoot: false
  capabilities:
    add:
    - ALL
  readOnlyRootFilesystem: false

service:
  type: ClusterIP
  grpcPort: 7100
  httpPort: 7110
  annotations: {}

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

nodeSelector: {}
tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - exchange
        topologyKey: kubernetes.io/hostname

# Application Configuration
config:
  backoffice:
    host: office-service-server.rgs-core.svc.cluster.local
    port: 7400
    isSecure: false

# Database configuration
database:
  host: 77.93.172.81  # External database
  port: 5432
  name: exchange
  user: exchange
  password: a0e525ea-5c4d-4d52-9816-852c84b64277
  connectionTimeout: "300s"
  compression: "zlib"
  pingInterval: "30s"
  minConnections: 100
  maxConnections: 200

# XE configuration (currency exchange)
xe:
  id: okBX34h8eLdRCC0RLW1DP83iLPZvBFBy
  key: YwRQOnlxzmSCKKTqhmszGgztGS7Y6IAT

# Exchange configuration
exchange:
  baseURL: ""
  enabled: false

# Tracer configuration
tracer:
  disabled: true
  url: jaeger-collector.monitoring.svc.cluster.local:14268/api/traces
  serviceName: exchange-service

# Health checks
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 5

# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1