# ArgoCD App of Apps - RGS Platform (CORRECTED)
# Remove the unnecessary main application since we're using ApplicationSets
---
# Infrastructure Applications
# NOTE: You need to either:
# 1. Create helm-charts/infrastructure/ charts, OR
# 2. Use public Helm charts from bitnami
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: postgresql
        namespace: rgs-infrastructure
        chart: postgresql
        repoURL: https://charts.bitnami.com/bitnami
        version: "12.1.9"
        valueslocation: $values/infrastructure-values/postgresql-values.yaml
      - name: redis
        namespace: rgs-infrastructure
        chart: redis
        repoURL: https://charts.bitnami.com/bitnami
        version: "17.3.14"
        valueslocation: $values/infrastructure-values/postgresql-values.yaml
      - name: rabbitmq
        namespace: rgs-infrastructure
        chart: rabbitmq
        repoURL: https://charts.bitnami.com/bitnami
        version: "11.1.3"
        valueslocation: $values/infrastructure-values/postgresql-values.yaml
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: infrastructure
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          valueFiles:
          - '{{valueslocation}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
---
# Core Services Applications (WORKING)
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-services-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: office
        namespace: rgs-core
        replicas: 2
      - name: exchange
        namespace: rgs-core
        replicas: 2
      - name: history
        namespace: rgs-core
        replicas: 2
      - name: launch
        namespace: rgs-core
        replicas: 2
      - name: overlord
        namespace: rgs-core
        replicas: 2
      - name: pfr
        namespace: rgs-core
        replicas: 2
      - name: rng
        namespace: rgs-core
        replicas: 2
      - name: adaptor
        namespace: rgs-core
        replicas: 2
  template:
    metadata:
      name: '{{name}}-service'
      namespace: argocd
      labels:
        app: '{{name}}'
        type: core-service
    spec:
      project: core-services
      source:
        repoURL: https://github.com/kay-ninja/rgs-k8s
        targetRevision: HEAD
        path: 'helm-charts/core-services/{{name}}'
        helm:
          parameters:
          - name: replicaCount
            value: '{{replicas}}'
          valueFiles:
          - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 3m
---
# Game Services Application Set (WORKING)
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: game-services-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/kay-ninja/rgs-k8s
      revision: HEAD
      directories:
      - path: helm-charts/game-services/*
  template:
    metadata:
      name: '{{path.basename}}-game'
      namespace: argocd
      labels:
        app: '{{path.basename}}'
        type: game-service
    spec:
      project: games
      source:
        repoURL: https://github.com/kay-ninja/rgs-k8s
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: rgs-games
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
---
# Istio Configuration Application (WORKING)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-config
  namespace: argocd
spec:
  project: networking
  source:
    repoURL: https://github.com/kay-ninja/rgs-k8s
    targetRevision: HEAD
    path: istio
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
---
# ArgoCD Projects (FIXED - removed spaces)
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Infrastructure components
  sourceRepos:
  - 'https://github.com/kay-ninja/rgs-k8s'
  - 'https://charts.bitnami.com/bitnami'  # Added for external charts
  destinations:
  - namespace: 'rgs-infrastructure'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core-services
  namespace: argocd
spec:
  description: Core RGS services
  sourceRepos:
  - 'https://github.com/kay-ninja/rgs-k8s'
  destinations:
  - namespace: 'rgs-core'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: games
  namespace: argocd
spec:
  description: Game services
  sourceRepos:
  - 'https://github.com/kay-ninja/rgs-k8s'
  destinations:
  - namespace: 'rgs-games'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: networking
  namespace: argocd
spec:
  description: Networking and traffic management
  sourceRepos:
  - 'https://github.com/kay-ninja/rgs-k8s'
  destinations:
  - namespace: 'istio-system'
    server: https://kubernetes.default.svc
  - namespace: 'rgs-*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
