# ArgoCD App of Apps - RGS Platform (FULLY FIXED)
---
# Infrastructure Applications - FIXED to use Bitnami charts directly with inline values
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: postgresql
        namespace: rgs-infrastructure
      - name: redis
        namespace: rgs-infrastructure
      - name: rabbitmq
        namespace: rgs-infrastructure
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: infrastructure
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: '{{name}}'
        targetRevision: |-
          {{- if eq .name "postgresql" }}12.1.9{{- end }}
          {{- if eq .name "redis" }}17.3.14{{- end }}
          {{- if eq .name "rabbitmq" }}11.1.3{{- end }}
        helm:
          values: |-
            {{- if eq .name "postgresql" }}
            auth:
              enablePostgresUser: true
              postgresPassword: "changeme-postgres-password"
              database: "rgs"
            initdbScripts:
              init.sql: |
                CREATE DATABASE office;
                CREATE DATABASE exchange;
                CREATE DATABASE history;
                CREATE DATABASE launch;
                CREATE DATABASE overlord;
                CREATE DATABASE pfr;
                CREATE DATABASE rng;
                CREATE DATABASE adaptor;
            primary:
              persistence:
                enabled: true
                size: 10Gi
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "250m"
                limits:
                  memory: "1Gi"
                  cpu: "500m"
            {{- end }}
            {{- if eq .name "redis" }}
            architecture: standalone
            auth:
              enabled: true
              password: "changeme-redis-password"
            master:
              persistence:
                enabled: true
                size: 5Gi
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "100m"
                limits:
                  memory: "512Mi"
                  cpu: "250m"
            {{- end }}
            {{- if eq .name "rabbitmq" }}
            auth:
              username: "rgs-user"
              password: "changeme-rabbitmq-password"
              erlangCookie: "changeme-erlang-cookie"
            persistence:
              enabled: true
              size: 5Gi
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "250m"
            {{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
---
# Core Services Applications - FIXED (removed problematic parameters)
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-services-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: office
        namespace: rgs-core
      - name: exchange
        namespace: rgs-core
      - name: history
        namespace: rgs-core
      - name: launch
        namespace: rgs-core
      - name: overlord
        namespace: rgs-core
      - name: pfr
        namespace: rgs-core
      - name: rng
        namespace: rgs-core
      - name: adaptor
        namespace: rgs-core
  template:
    metadata:
      name: '{{name}}-service'
      namespace: argocd
      labels:
        app: '{{name}}'
        type: core-service
    spec:
      project: core-services
      source:
        repoURL: https://github.com/kay-ninja/rgs-k8s
        targetRevision: HEAD
        path: 'helm-charts/core-services/{{name}}'
        helm:
          # REMOVED problematic parameters section
          valueFiles:
          - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 3m
---
# Game Services Application Set
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: game-services-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/kay-ninja/rgs-k8s
      revision: HEAD
      directories:
      - path: helm-charts/game-services/*
  template:
    metadata:
      name: '{{path.basename}}-game'
      namespace: argocd
      labels:
        app: '{{path.basename}}'
        type: game-service
    spec:
      project: games
      source:
        repoURL: https://github.com/kay-ninja/rgs-k8s
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: rgs-games
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
---
# Istio Configuration Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-config
  namespace: argocd
spec:
  project: networking
  source:
    repoURL: https://github.com/kay-ninja/rgs-k8s
    targetRevision: HEAD
    path: istio
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
---
# ArgoCD Projects
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Infrastructure components
  sourceRepos:
  - 'https://github.com/kay-ninja/rgs-k8s'
  - 'https://charts.bitnami.com/bitnami'
  destinations:
  - namespace: 'rgs-infrastructure'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core-services
  namespace: argocd
spec:
  description: Core RGS services
  sourceRepos:
  - 'https://github.com/kay-ninja/rgs-k8s'
  destinations:
  - namespace: 'rgs-core'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: games
  namespace: argocd
spec:
  description: Game services
  sourceRepos:
  - 'https://github.com/kay-ninja/rgs-k8s'
  destinations:
  - namespace: 'rgs-games'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: networking
  namespace: argocd
spec:
  description: Networking and traffic management
  sourceRepos:
  - 'https://github.com/kay-ninja/rgs-k8s'
  destinations:
  - namespace: 'istio-system'
    server: https://kubernetes.default.svc
  - namespace: 'rgs-*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
