apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: monitoring
data:
  tempo.yaml: |
    # Server configuration
    server:
      http_listen_port: 3200
      grpc_listen_port: 9095
      log_level: info
    
    # Distributor - receives traces from Istio
    distributor:
      receivers:
        zipkin:
          endpoint: 0.0.0.0:9411
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318
            grpc:
              endpoint: 0.0.0.0:4317
    
    # Ingester - writes traces
    ingester:
      max_block_duration: 5m
    
    # METRICS GENERATOR - WITH PROMETHEUS REMOTE WRITE
    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: rgs-gaming
          environment: dev
      storage:
        path: /var/tempo/generator/wal
        # REMOTE WRITE TO YOUR PROMETHEUS
        remote_write:
          - url: http://10.10.10.9:9090/api/v1/write
            send_exemplars: true
            headers:
              X-Scope-OrgID: rgs-gaming
      processor:
        # Service graphs
        service_graphs:
          max_items: 10000
          wait: 10s
        # Span metrics - will be sent to Prometheus
        span_metrics:
          dimensions:
            - service.namespace
            - service.name
            - span.name
            - span.kind
            - status.code
          # Histogram buckets for percentile calculations
          histogram_buckets: [0.002, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10]
      traces_storage:
        path: /var/tempo/generator/traces
    
    # Storage backend
    storage:
      trace:
        backend: local
        wal:
          path: /var/tempo/wal
        local:
          path: /var/tempo/blocks
    
    # Compactor
    compactor:
      compaction:
        block_retention: 48h
    
    # Query frontend
    query_frontend:
      search:
        max_duration: 0s
    
    # Overrides - enable processors globally
    overrides:
      metrics_generator_processors:
        - service-graphs
        - span-metrics
