apiVersion: v2
name: adaptor
description: RGS Adaptor Service - Game adaptor for Indian games
type: application
version: 1.0.0
appVersion: "3.0.5"
keywords:
  - rgs
  - adaptor
  - gaming
  - indian-adaptor
home: https://github.com/your-repo/rgs-k8s
maintainers:
  - name: Platform Team
    email: your-email@example.com