# PostgreSQL Values for RGS Platform
# Using Bitnami PostgreSQL chart

auth:
  enablePostgresUser: true
  postgresPassword: "changeme-postgres-password"
  database: "rgs"
  
# Create databases for all services
initdbScripts:
  init.sql: |
    CREATE DATABASE office;
    CREATE DATABASE exchange;
    CREATE DATABASE history;
    CREATE DATABASE launch;
    CREATE DATABASE overlord;
    CREATE DATABASE pfr;
    CREATE DATABASE rng;
    CREATE DATABASE adaptor;
    
    -- Grant permissions
    GRANT ALL PRIVILEGES ON DATABASE office TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE exchange TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE history TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE launch TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE overlord TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE pfr TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE rng TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE adaptor TO postgres;

primary:
  persistence:
    enabled: true
    size: 20Gi
    storageClass: "standard"  # Change based on your cluster
    
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
      
  nodeSelector: {}
  
  service:
    type: ClusterIP
    ports:
      postgresql: 5432
      
metrics:
  enabled: true
  serviceMonitor:
    enabled: false  # Enable if you have Prometheus operator
    
replication:
  enabled: false  # Enable for HA in production
  readReplicas: 2
  
volumePermissions:
  enabled: false
  
serviceAccount:
  create: true
  
commonAnnotations:
  app: postgresql
  component: database
  
# Network policy
networkPolicy:
  enabled: false  # Enable in production
  allowExternal: false
  explicitNamespacesSelector:
    matchLabels:
      name: rgs-core
